version: 0.2

phases:
  build:
    commands:
      - echo Build started on `date`
      - echo $CODEBUILD_SRC_DIR
      - mvn package
      - echo files `find .`
  post_build:
    commands:
      - aws cloudformation package --template-file deploy.yaml --s3-bucket beret-bucket --output-template-file NewSamTemplate.yaml
artifacts:
  type: zip
  files:
      - target/lambda-java-example-1.0-SNAPSHOT.jar
      - NewSamTemplate.yaml
